### ISSUE TITLE
can't see the current price

### ISSUE THREAD

**Issue by haexyh** [RanadeepPolavarapu/vscode-stocks#2]
# My Statusbar
![image](https://user-images.githubusercontent.com/22192159/73176605-1de2bb00-410d-11ea-87df-89bb617c8eea.png)

# Config (copy from your example)
![image](https://user-images.githubusercontent.com/22192159/73176517-ed028600-410c-11ea-91d1-d96a83962e3e.png)

**Comment by RanadeepPolavarapu** [comment]
Did you get a proper API key from IEXCloud?

You can also use Yahoo Finance as the data source. Please see the README for an example with Yahoo Finance (prefix symbols with `YF:`).

**Comment by haexyh** [comment]
I'm sorry for wasting your time. I haven't configured the Api key. Now it works. Sorry & thx

**Comment by RanadeepPolavarapu** [comment]
No problem. Glad it's working for you now.
